In [1]:
"""
SNA practical 1: Write a program to compute the following for a given a network:
1) number of edge
2) number of nodes
3) degree of nodes
4)node with lowest degree,
5)the adjacency list
6)matrix of the graph
"""

'\nSNA practical 1: Write a program to compute the following for a given a network:\n1) number of edge\n2) number of nodes\n3) degree of nodes\n4)node with lowest degree,\n5)the adjacency list\n6)matrix of the graph\n'

In [2]:
!pip install networkx


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import networkx as nx
import numpy as np

In [7]:
def compute_graph_properties(graph):
    
    #Number of edges
    num_edges = graph.number_of_edges()
    
    #Number of nodes
    num_nodes = graph.number_of_nodes()
    
    #Degree of node
    nodes_degree = dict(graph.degree())
    
    #Node with lowest degree
    min_degree_node = min(nodes_degree, key=nodes_degree.get)
    
    # Adjacency list
    adjacency_list = dict(graph.adjacency())
    
    #Adjacency Matrix
    adjacency_matrix = nx.adjacency_matrix(graph).todense()
    
    return num_edges, num_nodes, nodes_degree, min_degree_node, adjacency_list, adjacency_matrix


In [8]:
#Exmaple

G = nx.Graph()
G.add_edges_from([(1,4), (2,8), (3,6), (4,7), (5,3), (2,9), (7,6)])

#compute the graph properties
edges, nodes, degrees, min_degree_node, adj_list, adj_matrix = compute_graph_properties(G)

print("Number of edges:",edges)
print("Number of nodes:",nodes)
print("Degree of nodes:",degrees)
print("Mode with lowest degree:",min_degree_node)
print("Adjacency List:\n",adj_list)
print("Adjacency Matrix:\n",adj_matrix)

Number of edges: 7
Number of nodes: 9
Degree of nodes: {1: 1, 4: 2, 2: 2, 8: 1, 3: 2, 6: 2, 7: 2, 5: 1, 9: 1}
Mode with lowest degree: 1
Adjacency List:
 {1: {4: {}}, 4: {1: {}, 7: {}}, 2: {8: {}, 9: {}}, 8: {2: {}}, 3: {6: {}, 5: {}}, 6: {3: {}, 7: {}}, 7: {4: {}, 6: {}}, 5: {3: {}}, 9: {2: {}}}
Adjacency Matrix:
 [[0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]]
