In [1]:
"""
SNA Pratical 8 : Perform SVD analysis of a network
"""

'\nSNA Pratical 8 : Perform SVD analysis of a network\n'

In [2]:
pip install networkx

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import networkx as nx
import numpy as np
from scipy.linalg import svd

In [4]:
def svd_analysis(graph):
    adjacency_matrix = nx.to_numpy_array(graph)
    U, S, Vt = svd(adjacency_matrix)
    
    print("U matrix:")
    print(U)
    print("\n Singular matrix:")
    print(S)
    print("\n Transpose matrix:")
    print(Vt)
    
if __name__ == "__main__":
    G = nx.Graph()
    G.add_edges_from([(1,2), (2,3), (3,4), (4,1)])
    svd_analysis(G)

U matrix:
[[ 1.11022302e-16  7.07106781e-01  7.07106781e-01  0.00000000e+00]
 [-7.07106781e-01  1.66533454e-16  0.00000000e+00 -7.07106781e-01]
 [ 0.00000000e+00  7.07106781e-01 -7.07106781e-01  1.11022302e-16]
 [-7.07106781e-01 -5.55111512e-17 -5.55111512e-17  7.07106781e-01]]

 Singular matrix:
[2.00000000e+00 2.00000000e+00 2.22044605e-16 0.00000000e+00]

 Transpose matrix:
[[-7.07106781e-01  0.00000000e+00 -7.07106781e-01 -0.00000000e+00]
 [ 5.55111512e-17  7.07106781e-01 -1.11022302e-16  7.07106781e-01]
 [ 5.00000000e-01  5.00000000e-01 -5.00000000e-01 -5.00000000e-01]
 [ 5.00000000e-01 -5.00000000e-01 -5.00000000e-01  5.00000000e-01]]
